-- LingoPulse leaderboard
-- Chạy file này trong Supabase Dashboard > SQL Editor.

create table if not exists public.leaderboard_scores (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default 'Người học',
  points integer not null default 0 check (points >= 0),
  pronunciation_score integer not null default 0 check (pronunciation_score between 0 and 100),
  practice_count integer not null default 0 check (practice_count >= 0),
  updated_at timestamptz not null default now()
);

alter table public.leaderboard_scores enable row level security;

drop policy if exists "leaderboard_public_read" on public.leaderboard_scores;
create policy "leaderboard_public_read"
on public.leaderboard_scores for select
to anon, authenticated
using (true);

drop policy if exists "leaderboard_insert_own" on public.leaderboard_scores;
create policy "leaderboard_insert_own"
on public.leaderboard_scores for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "leaderboard_update_own" on public.leaderboard_scores;
create policy "leaderboard_update_own"
on public.leaderboard_scores for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create index if not exists leaderboard_scores_points_idx
on public.leaderboard_scores(points desc);


-- Learning attempts / analytics (optional but recommended for cross-device sync)
create table if not exists public.learning_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  activity_type text not null,
  word_id text,
  word_text text,
  score integer,
  correct boolean not null default false,
  xp integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.learning_attempts enable row level security;

drop policy if exists "attempts_read_own" on public.learning_attempts;
create policy "attempts_read_own"
on public.learning_attempts for select to authenticated
using (auth.uid() = user_id);

drop policy if exists "attempts_insert_own" on public.learning_attempts;
create policy "attempts_insert_own"
on public.learning_attempts for insert to authenticated
with check (auth.uid() = user_id);

create index if not exists learning_attempts_user_created_idx
on public.learning_attempts(user_id, created_at desc);

-- Per-user mastery state for spaced repetition
create table if not exists public.word_mastery (
  user_id uuid not null references auth.users(id) on delete cascade,
  word_id text not null,
  mastery integer not null default 0 check (mastery between 0 and 100),
  attempts integer not null default 0,
  correct integer not null default 0,
  wrong integer not null default 0,
  ease numeric(3,2) not null default 2.50,
  interval_days integer not null default 1,
  due_date date,
  last_score integer not null default 0,
  updated_at timestamptz not null default now(),
  primary key(user_id, word_id)
);

alter table public.word_mastery enable row level security;

drop policy if exists "word_mastery_own" on public.word_mastery;
create policy "word_mastery_own"
on public.word_mastery for all to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);
